In [ ]:
Data Cleaning in Pandas

In [1]:
import pandas as pd

In [69]:
df = pd.read_excel(r"D:\SQL\63. Dataset Customer Call List.xlsx.")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [6]:
df.drop(columns = 'Not_Useful_Column')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [7]:
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [9]:
df["Last_Name"].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
20      Skywalker
Name: Last_Name, dtype: object

In [24]:
df["Last_Name"].str.lstrip("...")

0     nan
1     nan
2     nan
3     nan
4     nan
5     nan
6     nan
7     nan
8     nan
9     nan
10    nan
11    nan
12    nan
13    nan
14    nan
15    nan
16    nan
17    nan
18    nan
19    nan
20    nan
Name: Last_Name, dtype: object

In [25]:
df["Last_Name"].str.lstrip(["/","..."])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
Name: Last_Name, dtype: float64

In [32]:
df["Last_Name"] = df["Last_Name"].str.lstrip(["/","..."])
df

KeyError: 'Last_Name'

In [23]:
#df["Last_Name"] = df["Last_Name"].str.lstrip("...")
#df["Last_Name"] = df["Last_Name"].str.lstrip("/")
#df["Last_Name"] = df["Last_Name"].str.lstrip("_")
# 1. Convert the column to string type, then clean it, and save it back to df
df["Last_Name"] = df["Last_Name"].astype(str).str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,nan,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,nan,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,nan,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,nan,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,nan,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,nan,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,nan,NaN,1209 South Street,No,No
7,1008,Sherlock,nan,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,nan,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,nan,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,nan,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,nan,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,nan,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,nan,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,nan,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,nan,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,nan,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,nan,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,nan,N/a,N/a,N/a,Yes
19,1020,Anakin,nan,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,nan,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [26]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,nan,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,nan,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,nan,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,nan,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,nan,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,nan,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,nan,NaN,1209 South Street,No,No
7,1008,Sherlock,nan,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,nan,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,nan,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,nan,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,nan,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,nan,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,nan,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,nan,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,nan,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,nan,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,nan,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,nan,N/a,N/a,N/a,Yes
19,1020,Anakin,nan,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,nan,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [33]:
df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

KeyError: 'Phone_Number'

In [44]:
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','',regex = 'True')
df

KeyError: 'Phone_Number'

In [43]:
# 1. Force-remove any trailing or leading whitespace from all column names

# 2. Clean the phone numbers safely by enabling regex=True
df["Phone_Number"] = df["Phone_Number"].astype(str).str.replace('[^a-zA-Z0-9]','')
df

KeyError: 'Phone_Number'

In [43]:
# 1. Force-remove any trailing or leading whitespace from all column names

# 2. Clean the phone numbers safely by enabling regex=True
df["Phone_Number"] = df["Phone_Number"].astype(str).str.replace('[^a-zA-Z0-9]','')
df

KeyError: 'Phone_Number'

In [50]:
df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

KeyError: 'Phone_Number'

In [51]:
df

0     123-545-5421
1     123/643/9775
2              NaN
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11             NaN
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17             NaN
18             N/a
19    876|678|3469
20    876|678|3469
Name: Phone_Number, dtype: object

In [55]:
str(df["Phone_Number"])

KeyError: 'Phone_Number'

In [56]:
# Use .astype(str) on the variable directly, without brackets
df = df.astype(str).str.replace('[^a-zA-Z0-9]', '', regex=True)
df

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8             Na
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18            Na
19    8766783469
20    8766783469
Name: Phone_Number, dtype: object

In [57]:
str(df["Phone_Number"])

KeyError: 'Phone_Number'

In [58]:
df = df.to_frame(name="Phone_Number")
df

   Phone_Number
0    1235455421
1    1236439775
2           nan
3    1235432345
4    8766783469
5    3047622467
6           nan
7    8766783469
8            Na
9    1235455421
10          nan
11          nan
12   1235432345
13   8766783469
14   3047622467
15   1235455421
16   1236439775
17          nan
18           Na
19   8766783469
20   8766783469

In [60]:
df["Phone_Number"].apply(lambda x: str(x))

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8             Na
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18            Na
19    8766783469
20    8766783469
Name: Phone_Number, dtype: object

In [61]:
df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18            Na--
19    876-678-3469
20    876-678-3469
Name: Phone_Number, dtype: object

In [65]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

    Phone_Number
0   123---5-4-5-
1   123---6-4-3-
2      nan------
3   123---5-4-3-
4   876---6-7-8-
5   304---7-6-2-
6      nan------
7   876---6-7-8-
8       Na------
9   123---5-4-5-
10     nan------
11     nan------
12  123---5-4-3-
13  876---6-7-8-
14  304---7-6-2-
15  123---5-4-5-
16  123---6-4-3-
17     nan------
18      Na------
19  876---6-7-8-
20  876---6-7-8-

In [67]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')

df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df

    Phone_Number
0   123---5-4-5-
1   123---6-4-3-
2           ----
3   123---5-4-3-
4   876---6-7-8-
5   304---7-6-2-
6           ----
7   876---6-7-8-
8           ----
9   123---5-4-5-
10          ----
11          ----
12  123---5-4-3-
13  876---6-7-8-
14  304---7-6-2-
15  123---5-4-5-
16  123---6-4-3-
17          ----
18          ----
19  876---6-7-8-
20  876---6-7-8-

In [70]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [71]:
df["Address"].str.split(',',1)

TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 were given

In [72]:
# Use the explicit keyword argument n=1
df["Address"].str.split(',', n=1)

0                     [123 Shire Lane,  Shire]
1                        [93 West Main Street]
2                         [298 Drugs Driveway]
3     [980 Paper Avenue,  Pennsylvania, 18503]
4                           [123 Dragons Road]
5                           [768 City Parkway]
6                          [1209 South Street]
7                              [98 Clue Drive]
8                           [123 Middle Earth]
9                [25th Main Street,  New York]
10                    [612 Shire Lane,  Shire]
11                      [2394 Hogwarts Avenue]
12                          [2039 Main Street]
13                          [343 City Parkway]
14                             [214 HR Avenue]
15                      [2395 Hogwarts Avenue]
16           [121 Paper Avenue,  Pennsylvania]
17                           [3498 Super Lane]
18                                       [N/a]
19              [910 Tatooine Road,  Tatooine]
20              [910 Tatooine Road,  Tatooine]
Name: Address, dtype: object

In [73]:
# Use the explicit keyword argument n=1
df["Address"].str.split(',', n=1, expand=True)

                       0                     1
0         123 Shire Lane                 Shire
1    93 West Main Street                  None
2     298 Drugs Driveway                  None
3       980 Paper Avenue   Pennsylvania, 18503
4       123 Dragons Road                  None
5       768 City Parkway                  None
6      1209 South Street                  None
7          98 Clue Drive                  None
8       123 Middle Earth                  None
9       25th Main Street              New York
10        612 Shire Lane                 Shire
11  2394 Hogwarts Avenue                  None
12      2039 Main Street                  None
13      343 City Parkway                  None
14         214 HR Avenue                  None
15  2395 Hogwarts Avenue                  None
16      121 Paper Avenue          Pennsylvania
17       3498 Super Lane                  None
18                   N/a                  None
19     910 Tatooine Road              Tatooine
20     910 Tatooine Road              Tatooine

In [74]:
# Use the explicit keyword argument n=1
df["Address"].str.split(',', n=2, expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None
20     910 Tatooine Road       Tatooine    None

In [77]:
# Use the explicit keyword argument n=1
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',', n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [78]:
df["Paying_Customer"].str.replace('Y','Yes')

KeyError: 'Paying_Customer'

In [79]:
# Remove any accidental leading or trailing spaces from the headers
df.columns = df.columns.str.strip()

# Run your replacement code
df["Paying_Customer"] = df["Paying_Customer"].str.replace('Y', 'Yes')
df

KeyError: 'Paying_Customer'

In [80]:
df.columns = df.columns.str.strip()
df["Paying_Customer"] = df["Paying_Customer"].str.replace('Y', 'Yes', regex=False)
df

KeyError: 'Paying_Customer'

In [81]:
df = df.str.replace('Y', 'Yes', regex=False)
df

AttributeError: 'DataFrame' object has no attribute 'str'

In [82]:
print(df.columns.tolist())

['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address', 'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column', 'Street_Address', 'State', 'Zip_Code']

In [84]:
df["Paying Customer"].str.replace('Y','Yes')

df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [85]:
df["Do_Not_Contact"] = df["Paying Customer"].str.replace('Y','Yes')

df["Do_Not_Contact"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,Y,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,Yes,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,Yes,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,Y,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,Y,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,N/a,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,None

In [89]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,Y,True,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,Yes,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,Yes,True,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,Y,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,Y,True,3498 Super Lane,,
18,1019,Creed,Braton,,,,,True,,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [88]:
df = df.replace('N/a','')
df = df.replace('NaN','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,Y,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,Yes,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,Yes,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,Y,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,Y,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,,,,True,,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,None

In [94]:
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
         df.drop(x, inplace = True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,Yes,False,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,Yes,True,612 Shire Lane,Shire,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
18,1019,Creed,Braton,,,,,True,,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [95]:
df["Do_Not_Contact"].str.replace('','N')

0     NYNeNsN
1         NNN
2         NNN
3     NYNeNsN
5     NYNeNsN
6         NNN
7         NNN
8     NYNeNsN
9     NYNeNsN
10    NYNeNsN
12    NYNeNsN
13    NYNeNsN
14        NNN
15        NNN
16    NYNeNsN
18          N
19    NYNeNsN
20    NYNeNsN
Name: Do_Not_Contact, dtype: object

In [96]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace = True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [97]:
df.reset_index()

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
5,7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
7,12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
8,13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
9,14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
10,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
11,16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
12,19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
13,20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [97]:
df.reset_index()

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
5,7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
7,12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
8,13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
9,14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
10,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
11,16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
12,19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
13,20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [99]:
df = df.reset_index(drop = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,Yes,True,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,N,False,93 West Main Street,,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,N,True,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,True,980 Paper Avenue,Pennsylvania,18503
4,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,,
5,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
6,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,Yes,True,25th Main Street,New York,
7,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,Yes,False,2039 Main Street,,
8,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,Yes,False,343 City Parkway,,
9,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
10,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
11,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,Yes,False,121 Paper Avenue,Pennsylvania,
12,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,
13,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,Yes,True,910 Tatooine Road,Tatooine,

In [107]:
for x in df.index:
    if df.loc[x, "Phonr_Number"] == '':
         df.drop(x, inplace = True)

df
df= df.dropna(subset = "Phone_Number"), inplace = True

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3393246496.py, line 6)